name: name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Go test
        run: |
          cd go
          go version
          go test ./gildedrose -v
          cd ..

      - name: build exec
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          cd go
          go build -o ./bin/texttest_fixture .
          cd ..

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Add pip & texttest
        run: |
          python -m pip install --upgrade pip
          pip install texttest

      - name: Run texttest
        run: |
          texttest -con
